services:

## MySQL
  mysqldb:
    container_name: mysql
    image: mysql:8.0.42
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql 

## API
  api:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - mysqldb
    environment:
      FLASK_ENV: development
    volumes:
      - .:/app